import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const screenshotsDir = path.join(__dirname, 'temporary screenshots');
const url = process.argv[2];
const label = process.argv[3] || 'mobile';
let n = 1;
while (fs.existsSync(path.join(screenshotsDir, `screenshot-${n}-${label}.png`))) n++;
const out = path.join(screenshotsDir, `screenshot-${n}-${label}.png`);
const browser = await puppeteer.launch({ headless:true, args:['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await page.goto(url, { waitUntil:'networkidle2', timeout:30000 });
await new Promise(r => setTimeout(r, 1200));
await page.screenshot({ path: out, fullPage: true });
await browser.close();
console.log(out);
